laravel/routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'panel', 'namespace' => 'admin'], function() {
    Route::get('login','LoginController@getLogin')->name('getLogin');
    Route::post('login','LoginController@postLogin')->name('postLogin');
    Route::get('logout','LoginController@getLogout')->name('getLogout');
});
Route::group(['prefix' => 'home', 'namespace' => 'FrontEnd'], function() {
    Route::get('logincus','LoginCustomerController@getLogin')->name('getLoginCus');
    Route::post('logincus','LoginCustomerController@postLogin')->name('postLoginCus');
    Route::get('logoutcus','LoginCustomerController@getLogout')->name('getLogoutCus');
});
Route::group(['middleware' => 'CheckAdminLogin','prefix' => 'panel'], function() {
    Route::get('/', function() {return view('admin.home');})->name('welcome');
});
Route::group(['middleware' => 'CheckCustomerLogin','prefix' => 'home'], function() {
    Route::get('/', function() {return view('frontend.home.index');});
});
Route::group(['middleware' => 'CheckAdminLogin','prefix' => 'panel','namespace' => 'admin'], function() {
    Route::resource('user', UserController::class);
    Route::resource('payment', PaymentController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('customer', CustomerController::class);
    Route::resource('product', ProductController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('brand', BrandController::class);
    Route::resource('product', ProductController::class);
    Route::get('category/productlist/{id}', 'CategoryController@productlist')->name('category.productlist');
    Route::get('/product/detail/{id}', 'ProductController@detail')->name('product.detail');
    Route::post('/ product/{product}', 'ProductController@active')->name('completedUpdate');
    Route::post('/ order/{order}', 'OrderController@active')->name('activeOrder');
    Route::get('/order_today', 'OrderController@index_today');
    Route::get('order', 'OrderController@index');
});
Route::group(['prefix' => '', 'namespace' => 'frontend'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('cart', 'HomeController@cart');
    Route::get('add-to-cart/{id}', 'HomeController@addToCart');
    Route::get('updateCart', 'HomeController@update')->name('updateCart');
    Route::get('shoplist', 'HomeController@shoplist')->name('shoplist');
    Route::get('remove-from-cart', 'HomeController@remove')->name('removeItem');
    Route::get('clear-all', 'HomeController@clear')->name('clear-all');
    Route::get('cart/checkout', 'CheckoutController@index');
    Route::get('singleproduct/{id}', 'HomeController@singleproduct')->name('singleproduct.index');
    Route::get('search', 'SearchController@search')->name('search');
    Route::get('searchByCategory', 'SearchController@search')->name('searchByCategory');
    Route::get('login', 'LoginCustomerController@getLogin')->name('login');
    Route::get('logout', 'LoginCustomerController@getLogout')->name('index.login');
    Route::get('account', 'AccountController@index');
    Route::post('cart/checkout/confirm', 'CheckoutController@confirm')->name('confirm');
    Route::post('create_account', 'AccountController@create')->name('account.create');
    Route::get('searchbycategory/{id}','SearchController@searhByCategory');

});
Route::group(['middleware' => 'CheckCustomerLogin', 'prefix' => '', 'namespace' => 'frontend'], function () {
    Route::get('cart/checkout', 'CheckoutController@index');
    Route::post('update_information' ,'AccountController@update_information')->name('update.informaton');
    Route::post('changepass','AccountController@changepass')->name('changepass');

});

/*
GET	    /product	        		index	product.index
GET	    /product/create	    		create	product.create
POST	/product					store	product.store
GET		/product/{product}			show	product.show
GET		/product/{product}/edit		edit	product.edit
PUT/PATCH	/product/{product}		update	product.update
DELETE	/ product/{product}			destroy	product.destroy
*/

laravel/app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;
    protected $table='brands';
    protected $fillable = [
        'name',
        'image',
        'desc',
        'status',
    ];

    public function owner(){
        return $this->belongsTo('User');
    }

    // In product model
    public function product(){
        return $this->hasMany('App\Models\Product','brand_id');
    }
}

laravel/app/Http/Controllers/admin/BrandController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Brand;
use App\Models\Product;
use Illuminate\Http\Request;
use Session;
use App\Classes\Helper;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('CheckAdminLogin');
        $this->viewprefix='admin.brand.';
        $this->viewnamespace='panel/brand';
    }
    public function index()
    {
        $Brands = Brand::all();
        return view($this->viewprefix.'index')->with('cate', $Brands);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->viewprefix.'create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $Brand = new Brand();
        $this->validate($request, [
            'name' => 'required',
            'desc' => 'required',
            'status' => 'required',
        ]);
        $Brand->name = $request->name;
        $Brand->image = Helper::imageUpload($request);
        $Brand->desc = $request->desc;
        $Brand->status = $request->status;
        if($Brand->save())
            Session::flash('message', 'successfully!');
        else
            Session::flash('message', 'Failure!');
        return redirect()->route('brand.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Brand  $Brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $Brand)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Brand  $Brand
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        return view($this->viewprefix.'edit')->with('brand', $brand);
        // return view($this->viewprefix.'edit',compact('product'));
    }
    public function update(Request $request, Brand $brand)
    {     /*
        $this->validate($request, [
            'name' => 'required',
            'price' => 'required',
            'discount' => 'required',
            'content' => 'required',
        ]);
        */

        $data=$request->validate([
            'name' => 'required',
            'desc' => 'required',
            'status' => 'required',
        ]);
        $data['image'] = Helper::imageUpload($request);
        if($brand->update($data))
            Session::flash('message', 'successfully!');
        else
            Session::flash('message', 'Failure!');
        return redirect()->route('brand.index');
    }
    public function destroy(Brand $brand)
    {
        if($brand->delete())
            Session::flash('message', 'successfully!');
        else
            Session::flash('message', 'Failure!');
        return redirect()->route('brand.index');
    }
    // public function productlist($id){
    //     $products = Brand::find($id)->product;
    //     return view('admin.Brand.productlist', compact('products'));
    // }
}

laravel/resources/views/admin/brand/create.blade.php
@extends('admin.layout')
@section('content')
<div class="main-content">

  <div class="page-content">
      <div class="container-fluid">

          <!-- start page title -->
          <div class="row">
              <div class="col-12">
                  <div class="page-title-box d-flex align-items-center justify-content-between">
                      <h4 class="mb-0 font-size-18">Add brand</h4>

                      <div class="page-title-right">
                          <ol class="breadcrumb m-0">
                              <li class="breadcrumb-item"><a href="javascript: void(0);">Ecommerce</a></li>
                              <li class="breadcrumb-item active">Add brand</li>
                          </ol>
                      </div>

                  </div>
              </div>
          </div>
          <!-- end page title -->

          <div class="row">
              <div class="col-12">
                  <div class="card">
                      <div class="card-body">

                          <h4 class="card-title">Basic Information</h4>
                          <p class="card-title-desc">Fill all information below</p>
                          <form data-select2-id="8" action="{{ route('brand.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                              <div class="row">
                                  <div class="col-sm-6">
                                      <div class="form-group">
                                        <label for="name">Name:</label>
                                        <input type="text" class="form-control" id="name" name="name">
                                      </div>
                                      <div class="custom-file">
                                        <label for="name">Desc:</label>
                                        <input type="text" class="form-control" id="desc" name="desc">
                                      </div>
                                      <div class="form-group">
                                        <label for="name" style="padding-top: 20px;">Status:</label>
                                        <input type="text" class="form-control" id="statuss" name="status">
                                      </div>
                                      <div class="form-group">
                                        <strong>Image:</strong>
                                        <input type="file" name="image" class="form-control" >

                                      </div>
                                      <div class="form-group">
                                        <button type="submit" class="btn btn-success">Add brand</button>
                                      </div>
                                  </div>
                              </div> <!-- end card-->
                          </form>
                      </div>
                  </div>
              </div>
          </div>
          <!-- end row -->

      </div> <!-- container-fluid -->
  </div>
  <!-- End Page-content -->
</div>
@endsection

laravel/resources/views/admin/brand/edit.blade.php
@extends('admin.layout')
@section('content')
<div class="main-content" style="padding-top: 150px">
  <div class="col-md-4">
      <form action="{{ route('brand.update',$brand->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
          <div class="form-group">
            <strong>Tên Loại:</strong>
            <input type="text" name="name" value="{{$brand->name}}" class="form-control">
          </div>
          <div class="form-group">
            <strong>Mô Tả:</strong>
            <input type="text" name="desc" value="{{$brand->desc}}" class="form-control">
          </div>
          <div class="form-group">
            <strong>Hình Ảnh:</strong>
            <input type="file" name="image" class="form-control" value="{{asset('images/'. $brand->image)}}">
          </div>
          <div class="form-group">
            <strong>Trạng Thái:</strong>
            <input type="text" name="status" value="{{$brand->status}}" class="form-control">
          </div>
          <div class="form-group">
              <input type="submit" value="Save" class="btn btn-primary" />
          </div>
      </form>
  </div>
</div>
<@stop

laravel/resources/views/admin/brand/index.blade.php
@extends('admin.layout')
@section('content')
<div class="main-content">

  <div class="page-content">
      <div class="container-fluid">

          <!-- start page title -->
          <div class="row">
              <div class="col-12">
                  <div class="page-title-box d-flex align-items-center justify-content-between">
                      <h4 class="mb-0 font-size-18">Nhãn Hiệu</h4>
                      <div class="page-title-right">
                          <ol class="breadcrumb m-0">
                              <li class="breadcrumb-item"><a href="javascript: void(0);">Ecommerce</a></li>
                              <li class="breadcrumb-item active">Nhãn Hiệu</li>
                          </ol>
                      </div>

                  </div>
              </div>
          </div>
          <!-- end page title -->

          <div class="row">
              <div class="col-12">
                  <div class="card">
                      <div class="card-body">
                          <div class="row mb-2">
                              <div class="col-sm-4">
                                  <div class="search-box mr-2 mb-2 d-inline-block">
                                      <div class="position-relative">
                                          <input type="text" class="form-control" placeholder="Search...">
                                          <i class="bx bx-search-alt search-icon"></i>
                                      </div>
                                  </div>
                              </div>
                              <div class="col-sm-8">
                                  <div class="text-sm-right">
                                      <button type="button" class="btn btn-success btn-rounded waves-effect waves-light mb-2 mr-2"><i class="mdi mdi-plus mr-1"></i><a href="{{route('brand.create')}}">Thêm Mới</a></button>
                                  </div>
                              </div><!-- end col-->
                          </div>

                          <div class="table-responsive">
                              <table class="table table-centered table-nowrap">
                                  <thead class="thead-light">
                                      <tr>
                                          <th style="width: 20px;">
                                              <div class="custom-control custom-checkbox">
                                                  <input type="checkbox" class="custom-control-input" id="customCheck1">
                                                  <label class="custom-control-label" for="customCheck1">&nbsp;</label>
                                              </div>
                                          </th>
                                          <th>Tên Nhãn Hiệu</th>
                                          <th>Logo</th>
                                          <th>Trạng Thái</th>
                                          <th>Sửa</th>
                                          <th>Xoá</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                    @foreach($cate ?? '' as $brand)
                                          <tr>
                                              <td>
                                                  <div class="custom-control custom-checkbox">
                                                      <input type="checkbox" class="custom-control-input" id="customCheck2">
                                                      <label class="custom-control-label" for="customCheck2">&nbsp;</label>
                                                  </div>
                                              </td>
                                              <td>{{$brand->name}}</td>
                                              <td>
                                                <img src="{{asset('images/'. $brand->image)}}" width="70" />
                                              </td>
                                              <td>
                                                  @if($brand->status == 1)
                                                          <button type="submit"  class="btn btn-warning" name="changeStatus" value="0"><i class="fa fa-lock"></i></button>
                                                  @else

                                                          <button type="submit" class="btn btn-warning" name="changeStatus" value="1"><i class="fa fa-unlock"></i></button>

                                                  @endif
                                              </td>
                                              <td>
                                                  <a href="{{route('brand.edit',$brand->id)}}" class="btn btn-primary">
                                                      <i class="fa fa-edit"></i>
                                                  </a>

                                              </td>
                                              <td>
                                                  <form action="{{ route('brand.destroy',$brand->id) }}" method="POST">
                                                      @csrf
                                                      @method('DELETE')
                                                      <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                                  </form>
                                              </td>
                                          </tr>
                                    @endforeach
                                  </tbody>
                              </table>
                          </div>
                          <ul class="pagination pagination-rounded justify-content-end mb-2">
                              <li class="page-item disabled">
                                  <a class="page-link" href="javascript: void(0);" aria-label="Previous">
                                      <i class="mdi mdi-chevron-left"></i>
                                  </a>
                              </li>
                              <li class="page-item active"><a class="page-link" href="javascript: void(0);">1</a></li>
                              <li class="page-item"><a class="page-link" href="javascript: void(0);">2</a></li>
                              <li class="page-item"><a class="page-link" href="javascript: void(0);">3</a></li>
                              <li class="page-item"><a class="page-link" href="javascript: void(0);">4</a></li>
                              <li class="page-item"><a class="page-link" href="javascript: void(0);">5</a></li>
                              <li class="page-item">
                                  <a class="page-link" href="javascript: void(0);" aria-label="Next">
                                      <i class="mdi mdi-chevron-right"></i>
                                  </a>
                              </li>
                          </ul>
                      </div>
                  </div>
              </div>
          </div>
          <!-- end row -->
      </div> <!-- container-fluid -->
  </div>
  <!-- End Page-content -->
  <!-- Modal -->
  <div class="modal fade exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Order Details</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                  </button>
              </div>
              <div class="modal-body">
                  <p class="mb-2">Product id: <span class="text-primary">#SK2540</span></p>
                  <p class="mb-4">Billing Name: <span class="text-primary">Neal Matthews</span></p>

                  <div class="table-responsive">
                      <table class="table table-centered table-nowrap">
                          <thead>
                              <tr>
                                  <th scope="col">Product</th>
                                  <th scope="col">Product Name</th>
                                  <th scope="col">Price</th>
                              </tr>
                          </thead>
                          <tbody>
                              <tr>
                                  <th scope="row">
                                      <div>
                                          <img src="assets\images\product\img-7.png" alt="" class="avatar-sm">
                                      </div>
                                  </th>
                                  <td>
                                      <div>
                                          <h5 class="text-truncate font-size-14">Wireless Headphone (Black)</h5>
                                          <p class="text-muted mb-0">$ 225 x 1</p>
                                      </div>
                                  </td>
                                  <td>$ 255</td>
                              </tr>
                              <tr>
                                  <th scope="row">
                                      <div>
                                          <img src="assets\images\product\img-4.png" alt="" class="avatar-sm">
                                      </div>
                                  </th>
                                  <td>
                                      <div>
                                          <h5 class="text-truncate font-size-14">Hoodie (Blue)</h5>
                                          <p class="text-muted mb-0">$ 145 x 1</p>
                                      </div>
                                  </td>
                                  <td>$ 145</td>
                              </tr>
                              <tr>
                                  <td colspan="2">
                                      <h6 class="m-0 text-right">Sub Total:</h6>
                                  </td>
                                  <td>
                                      $ 400
                                  </td>
                              </tr>
                              <tr>
                                  <td colspan="2">
                                      <h6 class="m-0 text-right">Shipping:</h6>
                                  </td>
                                  <td>
                                      Free
                                  </td>
                              </tr>
                              <tr>
                                  <td colspan="2">
                                      <h6 class="m-0 text-right">Total:</h6>
                                  </td>
                                  <td>
                                      $ 400
                                  </td>
                              </tr>
                          </tbody>
                      </table>
                  </div>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
          </div>
      </div>
  </div>

@stop